FROM debian:stable
MAINTAINER ops@trueability.com

RUN mkdir -p /var/lib/ta-data
ADD tiles/2x2tile_3.png /var/lib/ta-data/piece1.png
ADD scripts/docker/task1-mover.sh /usr/bin/mover.sh
RUN chmod 755 /usr/bin/mover.sh

ENTRYPOINT usr/bin/mover.sh
